# Generated by Django 5.2 on 2025-04-19 14:25

import django.db.models.deletion
import main.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DayOfWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('intro_image', models.ImageField(upload_to=main.models.excursion_intro_image_path)),
                ('overall_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8)),
                ('type', models.CharField(choices=[('Trip', 'Trip'), ('Ticket', 'Ticket')], max_length=10)),
                ('full_day', models.BooleanField(default=False)),
                ('on_request', models.BooleanField(default=False)),
                ('category', models.ManyToManyField(related_name='excursions', to='main.category')),
            ],
        ),
        migrations.CreateModel(
            name='ExcursionAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('max_guests', models.PositiveIntegerField()),
                ('booked_guests', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('price_per_adult', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_child', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_per_infant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='main.excursion')),
                ('weekdays', models.ManyToManyField(blank=True, to='main.dayofweek')),
            ],
        ),
        migrations.CreateModel(
            name='BookingAreas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nicosia_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('larnaca_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('famagusta_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('limassol_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paphos_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('general_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('excursion_availability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='main.excursionavailability')),
            ],
        ),
        migrations.CreateModel(
            name='ExcursionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=main.models.excursion_image_path)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.excursion')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_entries', to='main.excursion')),
            ],
        ),
        migrations.AddField(
            model_name='excursion',
            name='feedbacks',
            field=models.ManyToManyField(blank=True, related_name='excursions', to='main.feedback'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=255)),
                ('guest_email', models.EmailField(max_length=254)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('partial_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_adults', models.PositiveIntegerField()),
                ('total_kids', models.PositiveIntegerField()),
                ('total_infants', models.PositiveIntegerField()),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('excursion_availability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='main.excursionavailability')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='main.group')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='main.guide'),
        ),
        migrations.AddField(
            model_name='excursion',
            name='provider',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excursions', to='main.provider'),
        ),
        migrations.AddField(
            model_name='excursion',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='excursions', to='main.tag'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='main.booking')),
                ('payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='main.paymentmethod')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('representative', 'Representative'), ('client', 'Client')], max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Representative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='representative', to='main.userprofile')),
            ],
        ),
    ]
