# Generated by Django 5.2 on 2025-04-29 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8)),
            ],
        ),
        migrations.AlterField(
            model_name='group',
            name='guide',
            field=models.ForeignKey(limit_choices_to={'role': 'guide'}, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='main.userprofile'),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='provider',
            field=models.ForeignKey(limit_choices_to={'role': 'provider'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excursions_provider', to='main.userprofile'),
        ),
        migrations.RemoveField(
            model_name='representative',
            name='user_profile',
        ),
        migrations.RenameField(
            model_name='bookingareas',
            old_name='famagusta_price',
            new_name='ayianapa_protaras_price',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='bookingareas',
            name='general_price',
        ),
        migrations.RemoveField(
            model_name='bookingareas',
            name='nicosia_price',
        ),
        migrations.RemoveField(
            model_name='excursion',
            name='type',
        ),
        migrations.AddField(
            model_name='excursion',
            name='guide',
            field=models.ForeignKey(limit_choices_to={'role': 'guide'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excursions_guide', to='main.userprofile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='vat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('provider', 'Provider'), ('representative', 'Representative'), ('client', 'Client'), ('guide', 'Guide')], max_length=15),
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='excursion',
            name='pickup_point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excursions_pickup_point', to='main.pickuppoint'),
        ),
        migrations.DeleteModel(
            name='Guide',
        ),
        migrations.DeleteModel(
            name='Provider',
        ),
        migrations.DeleteModel(
            name='Representative',
        ),
    ]
