# Generated by Django 5.2 on 2025-06-03 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_pickuppoint_priority'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pickuppoint',
            options={'ordering': ['-priority']},
        ),
    ]
