# Generated by Django 5.2 on 2025-05-01 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_pickuppoint_alter_group_guide_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='guide',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'guide'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excursions_guide', to='main.userprofile'),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='pickup_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excursions_pickup_point', to='main.pickuppoint'),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='provider',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'provider'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excursions_provider', to='main.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('provider', 'Provider'), ('representative', 'Representative'), ('client', 'Client'), ('guide', 'Guide'), ('admin', 'Admin')], max_length=15),
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
