# Generated by Django 5.2 on 2025-06-03 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_pickuppoint_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pickuppoint',
            options={'ordering': ['priority']},
        ),
        migrations.AddField(
            model_name='booking',
            name='voucher_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='main.reservation'),
        ),
        migrations.AddField(
            model_name='dayofweek',
            name='booked',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
