# Generated by Django 5.2 on 2025-05-05 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_excursion_guide_alter_excursion_pickup_point_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailabilityDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date_day', models.DateField()),
                ('excursion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_days', to='main.excursion')),
            ],
        ),
    ]
