# Generated by Django 5.2 on 2025-05-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_availabilitydays'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuppoint',
            name='type',
            field=models.CharField(choices=[('hotel', 'Hotel'), ('port', 'Port'), ('airport', 'Airport'), ('bus_station', 'Bus Station'), ('other', 'Other')], default='other', max_length=15),
        ),
    ]
