# Generated by Django 5.2 on 2025-06-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_pickuppoint_options_booking_voucher_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayofweek',
            name='booked',
        ),
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
