# Generated by Django 5.2 on 2025-05-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_pickuppoint_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuppoint',
            name='google_maps_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='pickuppoint',
            name='location',
            field=models.CharField(choices=[('ayianapa_protaras', 'Ayia Napa - Protaras'), ('larnaca', 'Larnaca'), ('limassol', 'Limassol'), ('paphos', 'Paphos')], default='ayianapa_protaras', max_length=255),
        ),
    ]
