# Generated by Django 5.2 on 2025-05-05 09:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_pickuppoint_google_maps_link_pickuppoint_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuppoint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
