# Generated by Django 5.2 on 2025-06-03 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_booking_partial_paid_alter_booking_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='guest_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
