# Generated by Django 5.2 on 2025-06-05 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_booking_guest_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickupgroup',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_groups', to='main.region'),
        ),
    ]
