# Generated by Django 5.2 on 2025-05-05 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_pickuppoint_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickuppoint',
            name='google_maps_link',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
