# Generated by Django 5.2 on 2025-05-05 12:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_pickuppoint_google_maps_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
