# Generated by Django 5.2 on 2025-05-05 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_excursion_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='description',
            field=models.TextField(),
        ),
    ]
