# Generated by Django 5.2 on 2025-05-06 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_excursion_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='excursionavailability',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='excursionavailability',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='excursionavailability',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='excursion',
            name='pickup_point',
        ),
        migrations.AlterField(
            model_name='excursion',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=8),
        ),
        migrations.AddField(
            model_name='excursionavailability',
            name='region',
            field=models.ManyToManyField(blank=True, to='main.region'),
        ),
        migrations.AddField(
            model_name='excursion',
            name='pickup_point',
            field=models.ManyToManyField(blank=True, to='main.pickuppoint'),
        ),
    ]
