# Generated by Django 5.2 on 2025-05-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_region_excursionavailability_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excursionavailability',
            name='price_per_adult',
        ),
        migrations.RemoveField(
            model_name='excursionavailability',
            name='price_per_child',
        ),
        migrations.RemoveField(
            model_name='excursionavailability',
            name='price_per_infant',
        ),
        migrations.AddField(
            model_name='excursionavailability',
            name='ayianapa_protaras_adult_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='excursionavailability',
            name='ayianapa_protaras_child_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='excursionavailability',
            name='ayianapa_protaras_infant_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='excursionavailability',
            name='lca_adult_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='excursionavailability',
            name='lca_child_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='excursionavailability',
            name='lca_infant_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='excursionavailability',
            name='paphos_adult_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='excursionavailability',
            name='paphos_child_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='excursionavailability',
            name='paphos_infant_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='BookingAreas',
        ),
    ]
