# Generated by Django 5.2 on 2025-06-08 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_userprofile_vat_userprofile_region_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='group',
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='main.pickuppoint'),
        ),
    ]
