# Generated by Django 5.2 on 2025-07-14 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_booking_group_booking_pickup_point'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pickuppoint',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='excursionavailability',
            name='region',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='region',
        ),
        migrations.RemoveField(
            model_name='pickupgroup',
            name='region',
        ),
        migrations.RemoveField(
            model_name='pickupgroup',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='pickuppoint',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='pickuppoint',
            name='type',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='region',
        ),
        migrations.AddField(
            model_name='pickupgroup',
            name='cl_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pickupgroup',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='pickup_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='main.pickupgroup'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pickup_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='main.pickupgroup'),
        ),
        migrations.AlterField(
            model_name='excursionavailability',
            name='pickup_groups',
            field=models.ManyToManyField(blank=True, related_name='availabilities', to='main.pickupgroup'),
        ),
    ]
