# Generated by Django 5.2 on 2025-07-15 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_pickuppoint_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickuppoint',
            name='status',
        ),
    ]
