# Generated by Django 5.2 on 2025-05-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_region_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursionavailability',
            name='limassol_adult_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='excursionavailability',
            name='limassol_child_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='excursionavailability',
            name='limassol_infant_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
