# Generated by Django 5.2 on 2025-07-15 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_pickuppoint_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickupgroup',
            name='cl_id',
        ),
    ]
