# Generated by Django 5.2 on 2025-05-27 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_excursionavailability_limassol_adult_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='pickuppoint',
            name='address',
        ),
        migrations.RemoveField(
            model_name='pickuppoint',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pickuppoint',
            name='google_maps_link',
        ),
        migrations.RemoveField(
            model_name='pickuppoint',
            name='status',
        ),
        migrations.RemoveField(
            model_name='pickuppoint',
            name='type',
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotels', to='main.location')),
            ],
        ),
        migrations.AlterField(
            model_name='pickuppoint',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_points', to='main.location'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_id', models.CharField(max_length=255, unique=True)),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('flight_number', models.CharField(blank=True, max_length=255)),
                ('hotel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='main.hotel')),
            ],
        ),
    ]
