# Generated by Django 5.2 on 2025-07-15 16:24

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_pickupgroup_cl_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='excursions', to='main.category'),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='intro_image',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.excursion_intro_image_path),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='excursions', to='main.tag'),
        ),
    ]
