# Generated by Django 5.2 on 2025-05-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_location_remove_pickuppoint_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuppoint',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pickuppoint',
            name='google_maps_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='pickuppoint',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8),
        ),
        migrations.AddField(
            model_name='pickuppoint',
            name='type',
            field=models.CharField(choices=[('hotel', 'Hotel'), ('port', 'Port'), ('airport', 'Airport'), ('bus_station', 'Bus Station'), ('other', 'Other')], default='other', max_length=15),
        ),
    ]
