# Generated by Django 5.2 on 2025-07-23 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_excursion_category_alter_excursion_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='client_phone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='pickup_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='main.pickuppoint'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='total_adults',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='total_kids',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
