# Generated by Django 5.2 on 2025-05-27 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_excursion_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursion',
            name='provider',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'provider'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='excursions_provider', to='main.userprofile'),
        ),
    ]
