# Generated by Django 5.2 on 2025-07-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_reservation_client_email_reservation_client_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
