# Generated by Django 5.2 on 2025-05-28 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_excursion_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickuppoint',
            name='location',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='location',
        ),
        migrations.RenameField(
            model_name='excursionavailability',
            old_name='ayianapa_protaras_adult_price',
            new_name='adult_price',
        ),
        migrations.RenameField(
            model_name='excursionavailability',
            old_name='ayianapa_protaras_child_price',
            new_name='child_price',
        ),
        migrations.RenameField(
            model_name='excursionavailability',
            old_name='ayianapa_protaras_infant_price',
            new_name='infant_price',
        ),
        migrations.RemoveField(
            model_name='excursionavailability',
            name='lca_adult_price',
        ),
        migrations.RemoveField(
            model_name='excursionavailability',
            name='lca_child_price',
        ),
        migrations.RemoveField(
            model_name='excursionavailability',
            name='lca_infant_price',
        ),
        migrations.RemoveField(
            model_name='excursionavailability',
            name='limassol_adult_price',
        ),
        migrations.RemoveField(
            model_name='excursionavailability',
            name='limassol_child_price',
        ),
        migrations.RemoveField(
            model_name='excursionavailability',
            name='limassol_infant_price',
        ),
        migrations.RemoveField(
            model_name='excursionavailability',
            name='paphos_adult_price',
        ),
        migrations.RemoveField(
            model_name='excursionavailability',
            name='paphos_child_price',
        ),
        migrations.RemoveField(
            model_name='excursionavailability',
            name='paphos_infant_price',
        ),
        migrations.AddField(
            model_name='dayofweek',
            name='capacity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotel',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hotels', to='main.region'),
        ),
        migrations.RemoveField(
            model_name='excursionavailability',
            name='region',
        ),
        migrations.CreateModel(
            name='PickupGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('region', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_groups', to='main.region')),
            ],
        ),
        migrations.AddField(
            model_name='pickuppoint',
            name='pickup_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_points', to='main.pickupgroup'),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.AddField(
            model_name='excursionavailability',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='availabilities', to='main.region'),
        ),
    ]
