# Generated by Django 5.2 on 2025-07-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_reservation_departure_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursionavailability',
            name='pickup_points',
            field=models.ManyToManyField(blank=True, related_name='availabilities', to='main.pickuppoint'),
        ),
    ]
