# Generated by Django 5.2 on 2025-05-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_remove_pickuppoint_location_remove_hotel_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursionavailability',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8),
        ),
    ]
