# Generated by Django 5.2 on 2025-05-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_excursionavailability_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='hotel',
            name='phone_number',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
