# Generated by Django 5.2 on 2025-08-01 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_reservation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='guest_email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='guest_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
