# Generated by Django 5.2 on 2025-06-02 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_hotel_email_hotel_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availabilitydays',
            name='excursion',
        ),
        migrations.AddField(
            model_name='availabilitydays',
            name='excursion_availability',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availability_days', to='main.excursionavailability'),
        ),
        migrations.AlterField(
            model_name='pickuppoint',
            name='google_maps_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
