# Generated by Django 5.2 on 2025-08-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_booking_guest_email_alter_booking_guest_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilitydays',
            name='capacity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
