# Generated by Django 5.2 on 2025-06-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_availabilitydays_excursion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursionavailability',
            name='pickup_groups',
            field=models.ManyToManyField(blank=True, related_name='availabilities', to='main.pickupgroup'),
        ),
    ]
