# Generated by Django 5.2 on 2025-08-04 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_availabilitydays_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availabilitydays',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='dayofweek',
            name='capacity',
        ),
    ]
