# Generated by Django 5.2 on 2025-06-02 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_excursionavailability_pickup_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupGroupAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('excursion_availability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_group_availabilities', to='main.excursionavailability')),
                ('pickup_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_group_availabilities', to='main.pickupgroup')),
            ],
        ),
    ]
