# Generated by Django 5.2 on 2025-06-02 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_pickupgroupavailability'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickupgroupavailability',
            name='pickup_group',
        ),
        migrations.AddField(
            model_name='pickupgroupavailability',
            name='pickup_groups',
            field=models.ManyToManyField(blank=True, related_name='pickup_group_availabilities', to='main.pickupgroup'),
        ),
    ]
