# Generated by Django 5.2 on 2025-08-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_availabilitydays_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilitydays',
            name='capacity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
