# Generated by Django 5.2 on 2025-06-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_remove_pickupgroupavailability_pickup_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickupgroupavailability',
            name='pickup_groups',
        ),
        migrations.AddField(
            model_name='pickupgroupavailability',
            name='pickup_group_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
