# Generated by Django 5.2 on 2025-08-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_booking_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='partial_paid_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Card')], max_length=255, null=True),
        ),
    ]
