# Generated by Django 5.2 on 2025-06-02 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_remove_pickupgroupavailability_pickup_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickupgroupavailability',
            name='pickup_group_id',
        ),
        migrations.AddField(
            model_name='pickupgroupavailability',
            name='pickup_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_group_availabilities', to='main.pickupgroup'),
        ),
    ]
