# Generated by Django 5.2 on 2025-08-08 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_booking_partial_paid_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='partial_paid_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Card')], default=None, max_length=255, null=True),
        ),
    ]
