# Generated by Django 5.2 on 2025-06-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_remove_pickupgroupavailability_pickup_group_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excursionavailability',
            name='pickup_groups',
            field=models.ManyToManyField(blank=True, to='main.pickupgroup'),
        ),
    ]
