# Generated by Django 5.2 on 2025-06-02 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_excursionavailability_pickup_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excursion',
            name='pickup_point',
        ),
    ]
