# Generated by Django 5.2 on 2025-08-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_fix_partial_paid_method_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='deleteByUser',
            field=models.BooleanField(default=False),
        ),
    ]
