# Generated by Django 5.2 on 2025-08-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_userprofile_password_reset_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilitydays',
            name='booked_guests',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
