# Generated by Django 5.2 on 2025-09-01 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_availabilitydays_booked_guests'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='hotel',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='pickupgroup',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['created_at']},
        ),
    ]
