# Generated by Django 5.2 on 2025-10-02 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_booking_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excursion',
            name='feedbacks',
        ),
    ]
