# Generated by Django 5.2 on 2025-10-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_remove_excursion_feedbacks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='excursionimage',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.AddField(
            model_name='excursionimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='excursionimage',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order of image in gallery'),
        ),
    ]
