# Generated by Django 5.2 on 2025-10-09 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_alter_booking_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='client_profile',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'client'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='main.userprofile'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='first_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
