# Generated by Django 5.2 on 2025-10-14 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_reservation_client_profile_reservation_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['-date', 'name']},
        ),
        migrations.RemoveField(
            model_name='group',
            name='guide',
        ),
        migrations.AddField(
            model_name='group',
            name='bookings',
            field=models.ManyToManyField(blank=True, related_name='transport_groups', to='main.booking'),
        ),
        migrations.AddField(
            model_name='group',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='excursion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='main.excursion'),
        ),
    ]
