# Generated by Django 5.2 on 2025-10-15 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_bus_group_bus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['-date', 'status']},
        ),
        migrations.AddField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('sent', 'Sent'), ('not_sent', 'Not Sent')], default='not_sent', max_length=255),
        ),
    ]
