# Generated by Django 5.2 on 2025-10-15 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_alter_group_options_group_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bus',
            options={'ordering': ['name'], 'verbose_name': 'Bus', 'verbose_name_plural': 'Buses'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['-date', 'status'], 'verbose_name': 'Transport Group', 'verbose_name_plural': 'Transport Groups'},
        ),
    ]
