# Generated by Django 5.2 on 2025-10-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_alter_bus_options_alter_group_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='departure_time_updated',
            field=models.BooleanField(default=False),
        ),
    ]
