# Generated by Django 5.2 on 2025-10-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_reservation_departure_time_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickupgroup',
            name='priority',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pickuppoint',
            name='priority',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
