# Generated by Django 5.2 on 2025-10-23 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0043_pickupgroup_priority_pickuppoint_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='excursionavailability',
            name='pickup_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='excursionavailability',
            name='pickup_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='excursionavailability',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='availabilities', to='main.region'),
        ),
    ]
