# Generated by Django 5.2 on 2025-10-23 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_excursionavailability_pickup_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excursionavailability',
            name='region',
        ),
        migrations.AddField(
            model_name='excursionavailability',
            name='regions',
            field=models.ManyToManyField(blank=True, related_name='availabilities', to='main.region'),
        ),
    ]
