# Generated by Django 5.2 on 2025-10-29 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_remove_excursionavailability_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='regions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='main.region'),
        ),
    ]
