# Generated by Django 5.2 on 2025-10-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_booking_regions'),
    ]

    operations = [
        migrations.AddField(
            model_name='availabilitydays',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=255),
        ),
    ]
