# Generated by Django 5.2 on 2025-10-29 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_availabilitydays_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPickupPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_times', to='main.group')),
                ('pickup_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_pickup_times', to='main.pickuppoint')),
            ],
            options={
                'ordering': ['pickup_point__pickup_group__priority', 'pickup_point__priority', 'pickup_point__name'],
                'unique_together': {('group', 'pickup_point')},
            },
        ),
    ]
