# Generated by Django 5.2 on 2025-10-29 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_grouppickuppoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='guide',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'guide'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups_guide', to='main.userprofile'),
        ),
        migrations.AddField(
            model_name='group',
            name='provider',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'provider'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups_provider', to='main.userprofile'),
        ),
    ]
