# Generated by Django 5.2 on 2025-10-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_group_guide_group_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_superadmin',
            field=models.BooleanField(default=False),
        ),
    ]
