# Generated by Django 5.2 on 2025-10-30 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_userprofile_is_superadmin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excursion',
            name='guide',
        ),
    ]
