# Generated by Django 5.2 on 2025-10-31 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_remove_excursion_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='refferal_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('provider', 'Provider'), ('representative', 'Representative'), ('client', 'Client'), ('guide', 'Guide'), ('admin', 'Admin'), ('agent', 'Agent')], max_length=15),
        ),
    ]
