# Generated by Django 5.2 on 2025-10-31 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_remove_userprofile_refferal_code_referralcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='referral_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
