# Generated by Django 5.2 on 2025-11-24 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0054_booking_referral_discount_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='JCCGatewayConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Configuration name (e.g., 'JCC Sandbox Config' or 'JCC Production Config')", max_length=255)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox/Test'), ('production', 'Production')], default='sandbox', help_text='Environment type', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Only one active configuration should exist. Set others to inactive.')),
                ('username', models.CharField(help_text='JCC API username', max_length=255)),
                ('password', models.CharField(help_text='JCC API password', max_length=255)),
                ('register_url', models.URLField(help_text='URL for register.do endpoint (e.g., https://gateway-test.jcc.com.cy/payment/rest/register.do)', max_length=500)),
                ('status_url', models.URLField(help_text='URL for getOrderStatusExtended.do endpoint (e.g., https://gateway-test.jcc.com.cy/payment/rest/getOrderStatusExtended.do)', max_length=500)),
                ('default_currency', models.CharField(default='978', help_text='Currency code (ISO 4217 numeric, e.g., 978 for EUR, 840 for USD)', max_length=3)),
                ('default_language', models.CharField(default='en', help_text="Default language code (e.g., 'en', 'el')", max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'JCC Gateway Configuration',
                'verbose_name_plural': 'JCC Gateway Configurations',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='jcc_order_id',
            field=models.CharField(blank=True, help_text='JCC Payment Gateway order ID (orderId from register.do response)', max_length=255, null=True, unique=True),
        ),
    ]
