# Generated by Django 5.2 on 2025-11-25 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_jccgatewayconfig_booking_jcc_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='access_token',
            field=models.CharField(blank=True, db_index=True, help_text='Secure token for non-logged-in users to access their booking', max_length=64, null=True, unique=True),
        ),
    ]
