# Generated by Django 5.2 on 2025-11-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_emailsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailsettings',
            name='name_from',
            field=models.CharField(default='iTrip Knossos', max_length=255),
        ),
    ]
