# Generated by Django 5.2 on 2026-03-27 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0059_userprofile_email_verification_token_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingPickupTimeNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_time_sent', models.TimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=500)),
                ('recipient', models.EmailField(db_index=True, max_length=254)),
                ('email_kind', models.CharField(blank=True, db_index=True, help_text='E.g. booking_confirmation, cancellation, verification, admin_report', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Email log',
                'verbose_name_plural': 'Email logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='grouppickuppoint',
            options={'ordering': ['pickup_point__priority', 'pickup_point__name']},
        ),
        migrations.RemoveField(
            model_name='pickupgroup',
            name='priority',
        ),
        migrations.AddField(
            model_name='booking',
            name='confirmTime',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='confirm_time_at',
            field=models.DateTimeField(blank=True, help_text='When the user confirmed the pickup time', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='excursion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='main.excursion'),
        ),
        migrations.AddField(
            model_name='booking',
            name='guest_phone',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='reservation',
            name='confirm_departure_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='confirm_departure_time_at',
            field=models.DateTimeField(blank=True, help_text='When the user confirmed the departure time', null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='departure_confirm_token',
            field=models.CharField(blank=True, db_index=True, help_text='Token for one-click departure time confirmation from email', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='client_welcome_dismissed',
            field=models.BooleanField(default=False, help_text='Client has acknowledged the one-time welcome notification; do not show again.'),
        ),
        migrations.AlterField(
            model_name='emailsettings',
            name='name_from',
            field=models.CharField(default='iGoCyprus', max_length=255),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='excursions', to='main.category'),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='inactive', max_length=8),
        ),
        migrations.AlterField(
            model_name='excursion',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='excursions', to='main.tag'),
        ),
        migrations.AlterField(
            model_name='pickuppoint',
            name='priority',
            field=models.PositiveIntegerField(default=0, help_text='Lower value = earlier in the route. Used to order pickup stops on transport group detail, PDF, and CSV.'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('provider', 'Provider'), ('representative', 'Representative'), ('client', 'Client'), ('guide', 'Guide'), ('admin', 'Admin'), ('agent', 'Agent')], db_index=True, max_length=15),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['payment_status'], name='main_bookin_payment_ef2e29_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['date'], name='main_bookin_date_1e7163_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['created_at'], name='main_bookin_created_6fb4e5_idx'),
        ),
        migrations.AddField(
            model_name='bookingpickuptimenotification',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_time_notifications', to='main.booking'),
        ),
        migrations.AddField(
            model_name='bookingpickuptimenotification',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickup_time_notifications', to='main.group'),
        ),
        migrations.AlterUniqueTogether(
            name='bookingpickuptimenotification',
            unique_together={('booking', 'group')},
        ),
    ]
